version: '3.9'

services:
  flask-app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ".:/opt/flask-app"  # プロジェクトディレクトリ全体をマウント
    tty: true
    environment:
      TZ: Asia/Tokyo
      FLASK_APP: /opt/flask-app/run.py  # Flaskアプリケーションの起動ポイント
      FLASK_ENV: development
    command: flask run --host 0.0.0.0 --port 8000
    depends_on:
      - db
    platform: linux/amd64

  db:
    image: mysql:5.7
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    platform: linux/x86_64

volumes:
  db-data:
